version: "3"

services:
  web:
    image: xxx.dkr.ecr.us-east-2.amazonaws.com/demo-api/web:latest
    environment:
      - RAILS_ENV=production
    volumes:
      - web_socket:/api/shared/sockets
      - web_public:/api/public
    logging:
      driver: awslogs
      options:
        awslogs-group: demo-api-web
        awslogs-region: us-east-2
        awslogs-stream-prefix: demo-web

  nginx:
    image: xxx.dkr.ecr.us-east-2.amazonaws.com/demo-api/nginx:latest
    ports:
      - 80:80
    volumes:
      - web_socket:/var/www/html/api/shared/sockets
      - web_public:/var/www/html/api/public
    logging:
      driver: awslogs
      options: 
        awslogs-group: demo-api-nginx
        awslogs-region: us-east-2
        awslogs-stream-prefix: demo-api-nginx

volumes:
  web_socket:
  web_public: